UNDATA - Megan

In [1]:
import pandas as pd

In [2]:
import requests

Question:1
    Use the API to get all available data for the GDP per capita, PPP (constant 2017 international $) indicator. 
    Hint: this indicator has code "NY.GDP.PCAP.PP.KD". 
    Adjust the query parameters so that you can retrieve all available rows. Convert the results to a DataFrame.

In [3]:
endpoint = "http://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD"

In [4]:
params = {"format": "json", "per_page": "20000"}

In [5]:
res = requests.get(endpoint, params=params)

In [6]:
res

In [7]:
res = res.json()

In [8]:
df = pd.json_normalize(res[1])

In [9]:
cleaned_gdp = df[["date","value","country.value"]]

In [10]:
cleaned_gdp.columns = ["year","gdp","country"]

In [11]:
cleaned_gdp

       year          gdp                      country
0      2025          NaN  Africa Eastern and Southern
1      2024  4106.434140  Africa Eastern and Southern
2      2023  4083.993003  Africa Eastern and Southern
3      2022  4106.501907  Africa Eastern and Southern
4      2021  4056.113017  Africa Eastern and Southern
...     ...          ...                          ...
17485  1964          NaN                     Zimbabwe
17486  1963          NaN                     Zimbabwe
17487  1962          NaN                     Zimbabwe
17488  1961          NaN                     Zimbabwe
17489  1960          NaN                     Zimbabwe

[17490 rows x 3 columns]

Question 2:
    Now, use the API to get all available data for Life expectancy at birth, total (years). 
    This indicator has code "SP.DYN.LE00.IN". Again, convert the results to a DataFrame.

In [12]:
endpoint = "http://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN"

In [13]:
params = {"format": "json", "per_page": "20000"}

In [14]:
res = requests.get(endpoint, params=params)

In [15]:
res

In [16]:
res = res.json()

In [17]:
df = pd.json_normalize(res[1])

In [18]:
cleaned_exp = df[["date","value","country.value"]]

In [19]:
cleaned_exp.columns = ["year","LifeExp","country"]

In [20]:
cleaned_exp

       year    LifeExp                      country
0      2025        NaN  Africa Eastern and Southern
1      2024  65.349930  Africa Eastern and Southern
2      2023  65.146228  Africa Eastern and Southern
3      2022  64.487152  Africa Eastern and Southern
4      2021  62.979999  Africa Eastern and Southern
...     ...        ...                          ...
17485  1964  55.431000                     Zimbabwe
17486  1963  54.942000                     Zimbabwe
17487  1962  54.453000                     Zimbabwe
17488  1961  53.966000                     Zimbabwe
17489  1960  53.492000                     Zimbabwe

[17490 rows x 3 columns]

Question 3:
    Merge the two results DataFrames together. You may want to rename or drop columns prior to merging.

In [21]:
merged_data = pd.merge(left = cleaned_gdp, right = cleaned_exp, on = ['year','country'], how = "inner")

In [22]:
merged_data

       year          gdp                      country    LifeExp
0      2025          NaN  Africa Eastern and Southern        NaN
1      2024  4106.434140  Africa Eastern and Southern  65.349930
2      2023  4083.993003  Africa Eastern and Southern  65.146228
3      2022  4106.501907  Africa Eastern and Southern  64.487152
4      2021  4056.113017  Africa Eastern and Southern  62.979999
...     ...          ...                          ...        ...
17485  1964          NaN                     Zimbabwe  55.431000
17486  1963          NaN                     Zimbabwe  54.942000
17487  1962          NaN                     Zimbabwe  54.453000
17488  1961          NaN                     Zimbabwe  53.966000
17489  1960          NaN                     Zimbabwe  53.492000

[17490 rows x 4 columns]

Question 4: 
    You can also get more information about the available countries (region, capital city, income level classification, etc.) by using the Country API. 
    Use this API to pull in all available data. 
    Merge this with your other datasets. Use this to now remove the rows that correspond to regions and not countries.

In [42]:
endpoint = "https://api.worldbank.org/v2/country"

In [43]:
params = {"format": "json", "per_page": "20000"}

In [44]:
res = requests.get(endpoint, params=params)

In [45]:
res

In [46]:
res = res.json()

In [47]:
df = pd.json_normalize(res[1])

In [48]:
# cleaned_country = df[["name","capitalCity","region.value"]]

In [49]:
# cleaned_country

In [50]:
df_cleaned = df.dropna()

In [51]:
df_cleaned

,id,iso2Code,name,capitalCity,longitude,latitude,region.id,region.iso2code,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,ABW,AW,Aruba,Oranjestad,-70.0167,12.5167,LCN,ZJ,Latin America & Caribbean,,,,HIC,XD,High income,LNX,XX,Not classified
1,AFE,ZH,Africa Eastern and Southern,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,AFR,A9,Africa,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,AFW,ZI,Africa Western and Central,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
291,YEM,YE,"Yemen, Rep.",Sana'a,44.2075,15.352,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
292,ZAF,ZA,South Africa,Pretoria,28.1871,-25.746,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),UMC,XT,Upper middle income,IBD,XF,IBRD
293,ZMB,ZM,Zambia,Lusaka,28.2937,-15.3982,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDX,XI,IDA
294,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend

In [52]:
# df_cleaned = df[["name"]]

In [53]:
# df_cleaned.columns = ["country"]

In [54]:
df_cleaned

,id,iso2Code,name,capitalCity,longitude,latitude,region.id,region.iso2code,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,ABW,AW,Aruba,Oranjestad,-70.0167,12.5167,LCN,ZJ,Latin America & Caribbean,,,,HIC,XD,High income,LNX,XX,Not classified
1,AFE,ZH,Africa Eastern and Southern,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,AFR,A9,Africa,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,AFW,ZI,Africa Western and Central,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
291,YEM,YE,"Yemen, Rep.",Sana'a,44.2075,15.352,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
292,ZAF,ZA,South Africa,Pretoria,28.1871,-25.746,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),UMC,XT,Upper middle income,IBD,XF,IBRD
293,ZMB,ZM,Zambia,Lusaka,28.2937,-15.3982,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDX,XI,IDA
294,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend

In [56]:
merged_data3 = pd.merge(left = merged_data, right = df_cleaned, left_on = 'country', right_on = 'name', how = "inner")

In [57]:
merged_data3

,year,gdp,country,LifeExp,id,iso2Code,name,capitalCity,longitude,latitude,...,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,2025,NaN,Africa Eastern and Southern,NaN,AFE,ZH,Africa Eastern and Southern,,,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
1,2024,4106.434140,Africa Eastern and Southern,65.349930,AFE,ZH,Africa Eastern and Southern,,,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,2023,4083.993003,Africa Eastern and Southern,65.146228,AFE,ZH,Africa Eastern and Southern,,,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
3,2022,4106.501907,Africa Eastern and Southern,64.487152,AFE,ZH,Africa Eastern and Southern,,,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,2021,4056.113017,Africa Eastern and Southern,62.979999,AFE,ZH,Africa Eastern and Southern,,,,...,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17353,1964,NaN,Zimbabwe,55.431000,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17354,1963,NaN,Zimbabwe,54.942000,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17355,1962,NaN,Zimbabwe,54.453000,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17356,1961,NaN,Zimbabwe,53.966000,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend
17357,1960,NaN,Zimbabwe,53.492000,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,...,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend